### ISSUE TITLE
cart.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Alex-Marat/shop#1]
Почему-то 
 ngOnDestroy() {
    this.counterSubscription.unsubscribe();
  }
в самом конце компонента.
Так удобно?

**Comment by Alex-Marat** [comment]
Так сложилось у нас на проекте, что этот метод в самом конце  кода ( самый последний метод в жизненном цикле компонента). Хотя конечно это не принципиально.

**Comment by VZhyrytskiy** [comment]
ок
