### ISSUE TITLE
on

### ISSUE THREAD

**Issue by VZhyrytskiy** [Alex-Marat/shop#2]
Не удобно использовать префикс on для обработчиков событий в темплейте?

**Comment by Alex-Marat** [comment]
В общих ситуациях я пишу, например 
(click)='onClick()'
а в частных случаях пытаюсь передать функционал метода в названии, например
(increase)="increaseItems($event)" 
( + возможно просто забываю, что это кастомное событие)

**Comment by VZhyrytskiy** [comment]
ок
