### ISSUE TITLE
product.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Alex-Marat/shop#5]
Добавьте модификатор доступа для параметров конструктора и кода станет меньше и он станет читаемым.

**Comment by Alex-Marat** [comment]
Исправил.

**Comment by VZhyrytskiy** [comment]
Еще больше можно поправить

export class ProductModel implements Product {
  constructor(
    public id: string,
    public name: string,
    public description: string,
    public price: number,
    public category: Category,
    public count: number,
    public isAvailable: boolean,
    public discount: number = 0) {
      // this.id = id;
      // this.name = name;
      // this.description = description;
      // this.price = price;
      // this.category = category;
      // this.count = count;
      // this.isAvailable = isAvailable;
      // this.discount = discount || 0;
  }
}

**Comment by Alex-Marat** [comment]
спасибо, исправил
